version: "3.9"

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:5432
    volumes:
      - .:/code
    ports:
      - 5433:5432
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
 
volumes:
  postgres_data: